### ISSUE TITLE
Running the app in linux

### ISSUE THREAD

**Issue by rclUPC** [helloDestroyerOfWorlds/propeller_design_tools#2]
Hi,
I found this project really nice. I only wonder if it could be possible to be ran in linux. I am not a windows lover exactly.... I think that the only limitation is that XFOIL and XROTOR are windows executables. It could be done by using subprocess.Popen instead of STARTUPINFO in run_xfoil(), but I have not studied that carefully.
Can it be considered?
Regards
Robert

**Comment by helloDestroyerOfWorlds** [comment]
Hey Robert,

Sorry I've taken so long to get back.  

I'm a bit of an amateur, so I had to do some reading here.  I see what you were thinking, apparently the subprocess.STARTUPINFO is only for Windows.  The only reason I need to use that is to prevent the executable window from popping up dozens/hundreds of times, making it impossible to do anything other than wait for it to finish.

I initially tried removing the subprocess.STARTUPINFO call, and instead of passing startupinfo into subprocess.run() I instead passed creationflags=subprocess.CREATE_NO_WINDOW.  Not only did this not suppress the executable's windows for some unknown reason, I also then saw that this flag is also apparently only for Windows.

So then I tried passing creationflags=0x08000000 to subprocess.run(), which also seemed to not work for some unknown reason (everything worked except it didn't suppress the executable windows from popping up).

Finally, I switched to creating a subprocess.Popen() object, attempting to first pass it subprocess.CREATE_NO_WINDOW as creationflags, and then trying to pass 0x08000000.  Again, both seemed to work EXCEPT for actually suppressing the executable's windows.

I would gladly change the code if we can find something that works on both Windows and Linux, but right now it seems the only thing I can find that works is using subprocess.STARTUPINFO().

Any suggestions?

-Jake

**Comment by helloDestroyerOfWorlds** [comment]
If you don't mind I'm going to close this issue.  If you have any ideas ever just let me know.  And periodically check back with it by pip updating it, I just figured out how to make it automatically install all the dependencies itself which will be in the next update.  I'm starting to learn Linux so I may figure out a solution before too long...
